### ISSUE TITLE
Do GWAS summary statistics have to be independent / come from different samples?

### ISSUE THREAD

**Issue by MalteThodberg** [jrs95/hyprcoloc#12]
I'm analyzing a GWAS study where association has been calculated using the same samples across hundreds of phenotypes. So the GWAS summary statistics are not independent.

Is it still appropriate to run hyprcoloc in this case?

**Comment by jrs95** [comment]
Hi,

Yes, it is still appropriate to run hyprcoloc on GWAS analyses that are not independent. Although we have an option to account for the correlation, we recommend that you use the standard model (as if the GWAS were independent) as this is much faster and performed well in simulations compared to the correlated model.

Best wishes,

James

**Comment by MalteThodberg** [comment]
Thanks, I will give hyprcoloc a spin then!
