### ISSUE TITLE
Could not find tools necessary to compile a package

### ISSUE THREAD

**Issue by mightyphil2000** [jrs95/hyprcoloc#13]
Hi there! 

When I try to install hyprcoloc I get the error "Could not find tools necessary to compile a package". Do you know why I may be getting this error? 

> install_github("jrs95/hyprcoloc", build_opts = c("--no-resave-data", "--no-manual"), build_vignettes = TRUE)
Using github PAT from envvar GITHUB_PAT
Downloading GitHub repo jrs95/hyprcoloc@HEAD
Error: Failed to install 'hyprcoloc' from GitHub:
  Could not find tools necessary to compile a package
Call `pkgbuild::check_build_tools(debug = TRUE)` to diagnose the problem.

**Comment by mightyphil2000** [comment]
nevermind. I think I found the answer. I recently updated my mac OS and apparently I had to reinstall xcode. seems to work now.

**Comment by jrs95** [comment]
Hi,

Sorry to hear that you have had a problem downloading the package. 

To help us find the issue could you answer the following:
- What system are you using? If you are using Windows, do you have Rtools installed?
- Could you run the code suggested, pkgbuild::check_build_tools(debug = TRUE), and provide the outcome?

Best wishes,

James
