### ISSUE TITLE
hypRcoloc with 1500 phenotypes across 200 loci

### ISSUE THREAD

**Issue by MalteThodberg** [jrs95/hyprcoloc#14]
More of a question than an issue, but here we go:

I have run hypRcoloc on a dataset with ~1500 phenotypes measured on the same individuals. There are ~200 loci where at least 1 phenotype has genome-wide significant P-value < 5e-8. To make computations easier (/not crash my PC), for each loci, I extracted all phenotype with at least a suggestive P-value < 1e-6 and ran hypRcoloc with default parameters.

Results look pretty good, but I'm wondering about the priors: In the preprint, you run hyprcoloc in predefined LD-blocks. In my case, I run hypRcoloc at loci where I know at least one phenotype has significant signal.

Should I change prior.1 or prior.2 to something other than defaults in this case?

**Comment by jrs95** [comment]
Hi Malte,

I think the default priors should be okay in your situation. @cnfoley anything to add here?

Best wishes,

James

**Comment by cnfoley** [comment]
Hi Malte,

With so many traits and regions, I think it would be sensible to assess
sensitivity to the choice of priors. What I would do is:


   1. Run default analysis in each region
   2. (Within a region) For each cluster of colocalized traits identified -
   run a separate analysis assessing sensitivity to the default prior using
   the "sensitivity.plot". Section 3 in the vignette covers this.

If there are too many clusters for (2) to be pragmatically feasible let me
know and I'll send you a function which avoids plotting. For this, you will
have to input a 'decision rule' - deciding how much sensitivity to the
prior (i.e. how sensitive the custer structure is to the prior) that you
are willing to accept.

Good luck.

Chris
