### ISSUE TITLE
Betas

### ISSUE THREAD

**Issue by Vgene2** [jrs95/hyprcoloc#15]
Dear hyprcoloc team,

I would like to run hyprcoloc analysis using GWAS, eqtl and sqtl data. I have generated the file with beta columns for a list of variants for each dataset. My question is whether these betas need to correspond to the same effect allele in all three datasets. So if A is the effect allele in gwas and eqtl but C in the sqtl, do I need to change the sign of beta coefficient for sqtl to match the other two? Is such harmonization necessary? Finally, do the overlapping individuals between eqtl and sqtl data cause a issue in the analysis? Thank you.

**Comment by jrs95** [comment]
Hi,

If you use the the default (non-overlapping) method, then the data harmonisation described above is not essential (although I would always advise to do so, as it is good practice), as the approach uses squared Z-statistics. We recommend that the default approach is used even when you have overlapping samples, as it performed well in simulations with overlapping samples. So, in your case we would recommend the default method, and harmonisation of effect alleles is not necessary. 

Best wishes,

James
