### ISSUE TITLE
Warning messages on loading

### ISSUE THREAD

**Issue by MatthewMaher** [jrs95/hyprcoloc#16]
I just installed **hyprcoloc**, and whenever it is loaded it produces the excess warning messages below, which I don't think reflect a functional problem, but nonetheless, could they be eliminated? 

```
Warning messages:
1: replacing previous import 'Rmpfr::.__C__atomicVector' by 'Matrix::.__C__atomicVector' when loading 'hyprcoloc' 
2: replacing previous import 'Rmpfr::tcrossprod' by 'Matrix::tcrossprod' when loading 'hyprcoloc' 
3: replacing previous import 'Rmpfr::crossprod' by 'Matrix::crossprod' when loading 'hyprcoloc'
```
seemingly because both Rmpfr and Matrix are imported in their entirety and contain overlapping names.  

I suspect this can be corrected via changes to the import statements as discussed here:
https://stackoverflow.com/questions/41375150/imports-functions-with-the-same-name-but-from-different-package

Thanks

**Comment by jrs95** [comment]
Hi Matt,

I've fixed the issue, thanks for pointing this out.

Best wishes,

James
