### ISSUE TITLE
Supplying an LD matrix

### ISSUE THREAD

**Issue by HaglundA** [jrs95/hyprcoloc#17]
Hi,

I had a quick question regarding the use of your tool - I was playing around with the parameters and found that supplying your own LD matrix with correlation values (instead of the default ` diag(1, dim(effect.est)[1], dim(effect.est)[1])` ) makes no difference to the output with a number of different snp sets. All other parameters are set at default, perhaps I am missing something?

`hyprcoloc(x3, y3, trait.names = traits, snp.id = variants,snpscores = TRUE)`

versus:

`hyprcoloc(x3, y3, trait.names = traits, snp.id = variants,snpscores = TRUE,ld.matrix=ldmat)`

Thanks in advance!

Alex

**Comment by jrs95** [comment]
Hi Alex,

Apologies for the delay in answering your question.

The LD matrix is used to compute variant-specific priors when investigating correlated traits measured in overlapping samples, where the trait.cor matrix also has to be defined as non-identity. We still recommend using the standard approach (i.e. assuming non-overlapping samples) in most cases, as this model performed well even for traits that were highly correlated in overlapping samples and is much more computationally efficient.

Best wishes,

James
