### ISSUE TITLE
Error: vector memory exhausted (limit reached?)

### ISSUE THREAD

**Issue by HongyanR** [jrs95/hyprcoloc#19]
Hi, when I tried to run hyprcoloc, error showed up:
Error: vector memory exhausted (limit reached?)

I tried to increase the size in the .Renviron file and remove the big data files in the work environment, none works, any help would be appreciated

my pc is Macbook pro 16GRAM

Thanks
HONGYAN

**Comment by jrs95** [comment]
Hi Hongyan,

Apologies for the delayed response.

Sorry to hear that something appears to be awry.

Approximately, how big is the genetic region that you are analysing and for how many traits?

Best wishes,

James
