### ISSUE TITLE
How to specify sample overlap for binary traits?

### ISSUE THREAD

**Issue by annahutch** [jrs95/hyprcoloc#21]
Hi there. I was looking for more details on the sample.overlap parameter. Should this be a proportion, and how should one specify this for binary traits? 

Thanks in advance!
Anna

**Comment by jrs95** [comment]
Hi Anna,

Just the proportion of overlapping samples regardless of case/control status should suffice, although @cnfoley should be able to provide further details here.

Best wishes,

James
