### ISSUE TITLE
Trait correlation command line tool

### ISSUE THREAD

**Issue by annahutch** [jrs95/hyprcoloc#22]
Hi there,

In the vignette it states "Our command line tool can automatically compute trait correlation (using a tetrachoric correlation technique) and LD information. However, the R-package requires users to have this information to hand." but I cannot find any details of this command line tool. Could you please point me to where it is?

If I am unable to use this tool to compute trait correlations then what would you recommend? Would genetic correlation be an ok proxy for phenotypic correlation in this setting?

Thanks in advance,
Anna

**Comment by jrs95** [comment]
Hi Anna,

Apologies for the delayed response. 

Good spot! Unfortunately, I did not get around to finishing the command line tool during my post-doc prior to moving on to my current role. I'll remove this line in the vignette.

Genetic correlation will indeed do if you want to run the model accounting for trait correlation in overlapping samples. However, the standard model also performed well in simulations when there was trait correlation in overlapping samples, so we would recommend starting with this model in most scenarios.

Best wishes,

James
