### ISSUE TITLE
Enable to use in Asian populations?

### ISSUE THREAD

**Issue by 7JVST** [jrs95/hyprcoloc#23]
Hi there, 

I am planning to add colocalization method as a post-GWAS analysis in my study which is solely based on east Asian populations. I have noticed that “coloc”, “enloc” and “eCaviar” are being commonly used for colocalization analysis but all of which are being conducted in European GWAS or European dominant meta-analyses. Some stated that GTEx eQTL data, which might be a part of processing in these tools, was mainly generated from European populations, and thus,  it would be difficult to get the accurate results in Asian populations because of LD differences. May I know can I use HyprColoc for colocalization in Asian populations, otherwise, do you have any other recommendations for this issue?

**Comment by jrs95** [comment]
Hi,

All colocalization methodology is invariant to the ancestry of the population, so can be used for East Asian samples in the same way as it is used for European samples.

Best wishes,

James
