### ISSUE TITLE
Is it required for association results to have matched effect allele?

### ISSUE THREAD

**Issue by Zepeng-Mu** [jrs95/hyprcoloc#6]
Hi,

I am wondering whether hyprcoloc requires input datasets to have the same effect allele.

For example, I have a GWAS summary statistics and an eQTL dataset. Is it necessary to make sure that GWAS and eQTL have the same effect allele so that the sign of their effect size match?

Currently, I am not considering this and the result seem to be fine. But I just want to make sure that this does not make my results invalid. I know for some tools it is necessary to match effect alleles.

Thank you so much!

**Comment by jrs95** [comment]
Hi Zepeng-Mu,

No, the datasets do not need to be aligned to the same effect allele under the default recommended model.

Best wishes,

James
