### ISSUE TITLE
Feeding in ABFs directly?

### ISSUE THREAD

**Issue by shwetaramdas** [jrs95/hyprcoloc#9]
Hello,

I am running meta-analysis on a bunch of traits using MR-MEGA, and would like to feed in summary stats from these to hyprcoloc. However, MR-MEGA doesn't return beta/se(beta), but calculates a Bayes Factor internally. Is there any way I can feed in ABFs to hyprcoloc instead beta+se(betas)?

**Comment by jrs95** [comment]
Hi,

Good question, this is possible but I'm not sure we have the bandwidth to add this feature at the moment. @cnfoley thoughts?

Best wishes,

James
